import type { LiquidGlassCursorScript } from '../../system/overlays/LiquidGlassCursor'

const target = (name: string) => `[data-script-target="${name}"]`

export const interestProfilingScript: LiquidGlassCursorScript = {
  id: 'interest-profiling',
  scopeSelector: '.workbench-stage',
  initialDelayMs: 1400,
  steps: [
    {
      id: 'read-intro',
      action: 'click',
      selector: target('interest-get-started'),
      readMs: 1200,
      afterMs: 350,
    },
    {
      id: 'select-moving',
      action: 'click',
      selector: target('interest-reason-moving'),
      readMs: 1300,
      afterMs: 250,
    },
    {
      id: 'select-august',
      action: 'click',
      selector: target('interest-month-aug'),
      readMs: 650,
      afterMs: 250,
    },
    {
      id: 'select-ideas',
      action: 'click',
      selector: target('interest-reason-ideas'),
      readMs: 800,
      afterMs: 120,
    },
    {
      id: 'select-shopping',
      action: 'click',
      selector: target('interest-reason-shopping'),
      readMs: 250,
      afterMs: 200,
    },
    {
      id: 'continue-to-home-type',
      action: 'click',
      selector: target('interest-next'),
      readMs: 300,
      afterMs: 650,
    },
    {
      id: 'select-apartment',
      action: 'click',
      selector: target('interest-home-type-apartment'),
      readMs: 1200,
      afterMs: 250,
    },
    {
      id: 'select-square-footage',
      action: 'click',
      selector: target('interest-size-800-1-200-sq-ft'),
      readMs: 750,
      afterMs: 200,
    },
    {
      id: 'continue-to-living-with',
      action: 'click',
      selector: target('interest-next'),
      readMs: 300,
      afterMs: 650,
    },
    {
      id: 'select-partner',
      action: 'click',
      selector: target('interest-living-with-partner'),
      readMs: 1100,
      afterMs: 120,
    },
    {
      id: 'select-children',
      action: 'click',
      selector: target('interest-living-with-children'),
      readMs: 250,
      afterMs: 120,
    },
    {
      id: 'select-pets',
      action: 'click',
      selector: target('interest-living-with-pets'),
      readMs: 250,
      afterMs: 250,
    },
    {
      id: 'continue-to-final-preferences',
      action: 'click',
      selector: target('interest-next'),
      readMs: 300,
      afterMs: 700,
    },
    {
      id: 'select-sofa',
      action: 'click',
      selector: target('interest-product-sofas'),
      readMs: 1200,
      afterMs: 120,
    },
    {
      id: 'select-dining-table',
      action: 'click',
      selector: target('interest-product-dining-tables'),
      readMs: 250,
      afterMs: 240,
    },
    {
      id: 'select-living-room-style',
      action: 'click',
      selector: target('interest-topic-living-room-styling'),
      readMs: 650,
      afterMs: 280,
    },
    {
      id: 'select-interior-renovation',
      action: 'click',
      selector: target('interest-service-interior-renovation'),
      readMs: 650,
      afterMs: 280,
    },
    {
      id: 'complete',
      action: 'click',
      selector: target('interest-complete'),
      readMs: 500,
      afterMs: 700,
    },
  ],
}
